const __vite__mapDeps=(i,m=__vite__mapDeps,d=(m.f||(m.f=["assets/vendor-BFEQaPnH.js","assets/vendor-CWKLx11g.css"])))=>i.map(i=>d[i]);
import{a as $,S as R,b as B}from"./assets/vendor-BFEQaPnH.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&r(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const O="modulepreload",A=function(i){return"/goit-js-hw-12/"+i},p={},T=function(t,n,r){let e=Promise.resolve();if(n&&n.length>0){document.getElementsByTagName("link");const o=document.querySelector("meta[property=csp-nonce]"),a=(o==null?void 0:o.nonce)||(o==null?void 0:o.getAttribute("nonce"));e=Promise.allSettled(n.map(c=>{if(c=A(c),c in p)return;p[c]=!0;const d=c.endsWith(".css"),P=d?'[rel="stylesheet"]':"";if(document.querySelector(`link[href="${c}"]${P}`))return;const l=document.createElement("link");if(l.rel=d?"stylesheet":O,d||(l.as="script"),l.crossOrigin="",l.href=c,a&&l.setAttribute("nonce",a),document.head.appendChild(l),d)return new Promise((q,_)=>{l.addEventListener("load",q),l.addEventListener("error",()=>_(new Error(`Unable to preload CSS for ${c}`)))})}))}function s(o){const a=new Event("vite:preloadError",{cancelable:!0});if(a.payload=o,window.dispatchEvent(a),!a.defaultPrevented)throw o}return e.then(o=>{for(const a of o||[])a.status==="rejected"&&s(a.reason);return t().catch(s)})},I="54182514-8e89b17f0b2f5be4b382492b8",x="https://pixabay.com/api/";async function g(i,t=1,n=15){try{return(await $.get(x,{params:{key:I,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:n}})).data}catch(r){throw console.error("Pixabay API error:",r),r}}const h=document.querySelector(".gallery");let H=new R(".gallery a");const L=document.querySelector(".load-more");function w(i,t=!1){const n=i.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p>Likes: ${r.likes}</p>
        <p>Views: ${r.views}</p>
        <p>Comments: ${r.comments}</p>
        <p>Downloads: ${r.downloads}</p>
      </div>
    </li>
  `).join("");t?h.insertAdjacentHTML("beforeend",n):h.innerHTML=n,H.refresh()}function U(){h.innerHTML=""}function b(){document.querySelector(".loader").classList.remove("hidden")}function v(){document.querySelector(".loader").classList.add("hidden")}function C(){B.error({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}function M(){L.classList.remove("hidden")}function S(){L.classList.add("hidden")}const E=document.querySelector(".form"),j=E.querySelector('input[name="search-text"]'),k=document.querySelector(".load-more");let f="",u=1;const m=15;let y=0;E.addEventListener("submit",async i=>{if(i.preventDefault(),f=j.value.trim(),!!f){u=1,U(),S(),b();try{const t=await g(f,u,m);y=t.totalHits,t.hits.length===0?C():(w(t.hits),u*m<y&&M())}catch(t){console.error(t)}finally{v()}}});k.addEventListener("click",async()=>{u+=1,b();try{const i=await g(f,u,m);w(i.hits,!0);const t=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),u*m>=y&&(S(),T(async()=>{const{default:n}=await import("./assets/vendor-BFEQaPnH.js").then(r=>r.i);return{default:n}},__vite__mapDeps([0,1])).then(({default:n})=>{n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}))}catch(i){console.error(i)}finally{v()}});
//# sourceMappingURL=index.js.map
