const __vite__mapDeps=(i,m=__vite__mapDeps,d=(m.f||(m.f=["assets/vendor-BFEQaPnH.js","assets/vendor-CWKLx11g.css"])))=>i.map(i=>d[i]);
import{a as g,S as w,b as L}from"./assets/vendor-BFEQaPnH.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const r of n.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&l(r)}).observe(document,{childList:!0,subtree:!0});function t(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function l(e){if(e.ep)return;e.ep=!0;const n=t(e);fetch(e.href,n)}})();const b="modulepreload",v=function(s){return"/goit-js-hw-12/"+s},d={},E=function(o,t,l){let e=Promise.resolve();if(t&&t.length>0){document.getElementsByTagName("link");const r=document.querySelector("meta[property=csp-nonce]"),i=(r==null?void 0:r.nonce)||(r==null?void 0:r.getAttribute("nonce"));e=Promise.allSettled(t.map(a=>{if(a=v(a),a in d)return;d[a]=!0;const u=a.endsWith(".css"),h=u?'[rel="stylesheet"]':"";if(document.querySelector(`link[href="${a}"]${h}`))return;const c=document.createElement("link");if(c.rel=u?"stylesheet":b,u||(c.as="script"),c.crossOrigin="",c.href=a,i&&c.setAttribute("nonce",i),document.head.appendChild(c),u)return new Promise((p,y)=>{c.addEventListener("load",p),c.addEventListener("error",()=>y(new Error(`Unable to preload CSS for ${a}`)))})}))}function n(r){const i=new Event("vite:preloadError",{cancelable:!0});if(i.payload=r,window.dispatchEvent(i),!i.defaultPrevented)throw r}return e.then(r=>{for(const i of r||[])i.status==="rejected"&&n(i.reason);return o().catch(n)})},S="54182514-8e89b17f0b2f5be4b382492b8",P="https://pixabay.com/api/";async function q(s){try{return(await g.get(P,{params:{key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}catch(o){throw console.error("Pixabay API error:",o),o}}const f=document.querySelector(".gallery");let _=new w(".gallery a");function $(s){const o=s.map(t=>`
    <li class="gallery-item">
      <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p>Likes: ${t.likes}</p>
        <p>Views: ${t.views}</p>
        <p>Comments: ${t.comments}</p>
        <p>Downloads: ${t.downloads}</p>
      </div>
    </li>
  `).join("");f.innerHTML=o,_.refresh()}function O(){f.innerHTML=""}function R(){document.querySelector(".loader").classList.remove("hidden")}function A(){document.querySelector(".loader").classList.add("hidden")}function T(){L.error({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}const m=document.querySelector(".form"),x=m.querySelector('input[name="search-text"]');m.addEventListener("submit",async s=>{s.preventDefault();const o=x.value.trim();if(o){O(),R();try{const t=await q(o);t.length===0?T():$(t)}catch(t){console.error(t),E(async()=>{const{default:l}=await import("./assets/vendor-BFEQaPnH.js").then(e=>e.i);return{default:l}},__vite__mapDeps([0,1])).then(({default:l})=>{l.error({title:"Error",message:"Something went wrong while fetching images!",position:"topRight"})})}finally{A()}}});
//# sourceMappingURL=index.js.map
