import{a as v,S,i}from"./assets/vendor-BBiwxaSv.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&r(d)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const q="54182514-8e89b17f0b2f5be4b382492b8",P="https://pixabay.com/api/";async function h(s,t=1,a=15){const r=Math.max(a,15);try{return(await v.get(P,{params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r}})).data}catch(e){throw console.error("Pixabay API error:",e),e}}const u=document.querySelector(".gallery");let R=new S(".gallery a");const p=document.querySelector(".load-more");function m(s,t=!1){const a=s.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
      </a>
      <div class="info">
        <p>Likes: ${r.likes}</p>
        <p>Views: ${r.views}</p>
        <p>Comments: ${r.comments}</p>
        <p>Downloads: ${r.downloads}</p>
      </div>
    </li>
  `).join("");t?u.insertAdjacentHTML("beforeend",a):u.innerHTML=a,R.refresh()}function M(){u.innerHTML=""}function y(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function B(){i.error({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}function L(){p.classList.remove("hidden")}function b(){p.classList.add("hidden")}const w=document.querySelector(".form"),E=w.querySelector('input[name="search-text"]'),$=document.querySelector(".load-more");let l="",n=1;const c=15;let f=0;w.addEventListener("submit",async s=>{if(s.preventDefault(),l=E.value.trim(),!!l){n=1,M(),b(),y();try{const t=await h(l,n,c);if(f=t.totalHits,t.hits.length===0){B();return}m(t.hits),n*c<f?L():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}});$.addEventListener("click",async()=>{n+=1,b(),y();try{const s=await h(l,n,c);m(s.hits,!0);const t=document.querySelector(".gallery li").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),n*c<f?L():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch{i.error({title:"Error",message:"Failed to load more images.",position:"topRight"})}finally{g()}});
//# sourceMappingURL=index.js.map
